---

- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Set selinux bool for haproxy
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
  when:
    - ansible_selinux
    - ansible_selinux is defined
    - ansible_selinux.status == 'enabled'
