---

- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Set selinux bool for haproxy
  when:
    - ansible_facts["selinux"] is defined
    - ansible_facts["selinux"]["status"] == 'enabled'
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
