---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/ansible-lint.yml@bfe64abb826038f469b5292f19d2b0887f60f6ad # main
