---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/ansible-lint.yml@aea0351d17436239313b7a5aad775bd20bbe8efc # main
